mdev-35569 attempt
needs update to remove bits.

saving to file is ugly

only partially functional with skip-tz

11.7 and 10.11 errors

2024-12-17 05:25:00+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
2024-12-17  5:25:00 0 [Warning] mariadbd: io_uring_queue_init() failed with ENOSYS: check seccomp filters, and the kernel version (newer than 5.1 required)
2024-12-17  5:25:00 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
ERROR: 1698  Access denied for user 'boot'@'connecting host'
2024-12-17  5:25:00 0 [ERROR] Aborting